[package]
name = "web_spf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spf = { git="https://github.com/SimplePixelFont/spf.rs.git" }
render_spf = { path = "./crates/render_spf" }
js-sys = "0.3.77"
web-sys = "0.3.77"
wasm-bindgen = "0.2.100"