/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_tableentry_colors: (a: number) => [number, number];
export const __wbg_set_tableentry_colors: (a: number, b: number, c: number) => void;
export const __wbg_tableentry_free: (a: number, b: number) => void;
export const __wbg_texture_free: (a: number, b: number) => void;
export const get_printer_colors: (a: number, b: number) => [number, number];
export const load_layout_from_file: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const loaded: () => number;
export const set_printer_color: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const texture_height: (a: number) => number;
export const texture_new: () => number;
export const texture_set_height: (a: number, b: number) => void;
export const texture_set_texture_data: (a: number, b: number, c: number) => void;
export const texture_set_width: (a: number, b: number) => void;
export const texture_texture_data: (a: number) => [number, number];
export const texture_width: (a: number) => number;
export const __wbg_badgesocket_free: (a: number, b: number) => void;
export const __wbg_printsocket_free: (a: number, b: number) => void;
export const badgesocket_new: () => number;
export const badgesocket_set_color: (a: number, b: number, c: number) => void;
export const badgesocket_set_label: (a: number, b: number) => void;
export const badgesocket_set_label_color: (a: number, b: number, c: number) => void;
export const badgesocket_set_logo: (a: number, b: number) => void;
export const badgesocket_set_message: (a: number, b: number) => void;
export const print_badge: (a: number) => number;
export const print_text: (a: number) => number;
export const printsocket_new: () => number;
export const printsocket_set_letter_spacing: (a: number, b: number) => void;
export const printsocket_set_processor: (a: number, b: any) => void;
export const printsocket_set_text: (a: number, b: number, c: number) => void;
export const spf_core_layout_from_data: (a: number, b: number, c: number) => number;
export const spf_core_layout_to_data: (a: number, b: number) => number;
export const spf_free_data: (a: number) => void;
export const spf_free_layout: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
